### ISSUE TITLE
License of the fuzzer/* files?

### ISSUE THREAD

**Issue by OdyX** [alexpevzner/sane-airscan#100]
Between 0.99.19 and 0.99.20, `fuzzer/*` files were added with this header:
```
// Copyright 2020 The Chromium OS Authors. All rights reserved.
// See LICENSE for license terms and conditions.
```

It's not clear whether a `fuzzer/LICENSE` was forgotten, or if that points to `./LICENSE`. Could you clarify under which License these files are shipped?

**Comment by alexpevzner** [comment]
@yetamrra,

could you please look to this issue?

**Comment by yetamrra** [comment]
That was meant to refer to the project top-level LICENSE.  I'll send a quick PR to clarify.

**Comment by alexpevzner** [comment]
Thank you, @yetamrra,

@OdyX, I've created 0.99.21 release with the only difference in updated license information in the fuzzer files
