### ISSUE TITLE
SaneDroid or InSane compatiblty?

### ISSUE THREAD

**Issue by markosjal** [alexpevzner/sane-airscan#11]
I tried the two android apps SaneDroid and InSane but unable to get ether to work with this back-end . I was wondering if other had any luck.
after attempting to connect I see

`$ systemctl status saned.socket
● saned.socket - saned incoming socket
   Loaded: loaded (/etc/systemd/system/saned.socket; enabled; vendor preset: enabled)
   Active: active (listening) since lun 2020-02-10 09:45:00 CST; 35s ago
   Listen: [::]:6566 (Stream)
 Accepted: 1; Connected: 0

feb 10 09:45:00 HDTVStreamersIn systemd[1]: Listening on saned incoming socket.
feb 10 09:45:28 HDTVStreamersIn systemd[1]: saned.socket: Too many incoming connections (1), refusing connection attempt.`

**Comment by alexpevzner** [comment]
SaneDroid and InSane are clients for SANE's own network protocol (and SANE daemon that implements this protocol).

**Comment by alexpevzner** [comment]
Seems I can close this issue
