### ISSUE TITLE
An HP ENVY Photo 7855

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#110]
https://answers.launchpad.net/hplip/+question/694590

> ty=HP ENVY Photo 7800 series

After an excursion via the printer's Webscan, the user eventually said

> ...and noticed that in the title bar there a scan button, which I click and lo! it scanned nicely.

Cheers,

Brian.

**Comment by alexpevzner** [comment]
Thank you, Brian.

3 more devices, and we will have 100 devices in the list! :-)
