### ISSUE TITLE
Should POSTed XML have Scan:intent ?

### ISSUE THREAD

**Issue by markosjal** [alexpevzner/sane-airscan#12]
In scanner Capabilities I see
`<scan:SupportedIntents>
<scan:Intent>Document</scan:Intent>
<scan:Intent>TextAndGraphic</scan:Intent>
<scan:Intent>Photo</scan:Intent>
<scan:Intent>Preview</scan:Intent>
</scan:SupportedIntents>`

Should a preview POSTed to the scanner show 
`<scan:Intent>Preview</scan:Intent>`

I was looking on the traces you posted and none seem to have this in the POST , but I have no idea what generated the POST requests.  However it is there and if appropriate to use, perhaps should be used?

**Comment by alexpevzner** [comment]
I've actually never tried. This is not always easy to guess how features listed in capabilities map to parameters in request.
