### ISSUE TITLE
Kyocera ECOSYS M5521cdw - Compatibility Report

### ISSUE THREAD

**Issue by Nocifer** [alexpevzner/sane-airscan#123]
I can confirm that the Kyocera M5521cdw MFP works with both eSCL and WSD protocols (so I guess that would mean that its big brother, the Kyocera M5526cdw, also works with both of them and not only with eSCL as already reported on the compatibility list).

With regard to WSD, I initially also faced the issue described in footnote [5], i.e. needing to initiate scanning from the device; I seem to remember that I somehow resolved that, but it's been a couple of months since I bought and actively tested the machine so I could be remembering this wrong. I'll try to confirm it sometime in the next few days and get back to you.

eSCL on the other hand works flawlessly.

**Comment by alexpevzner** [comment]
Thank you very much for notification -- I've updated the list.

I seem to remember that a while ago I've tested scanning from Windows machine, and it didn't require scan initiation from the device. However when I've faced this issue during sane-airscan development, I've retested again with Windows, and issue was already present. So who knows, either I've missed something during my first test with Windows, or may be device has silently upgraded its firmware and changed its behaviour.

Anyway, if it can be somehow fixed, I'm interested to know a solution.

P.S. M2040dn/M5521cdw/M5526cdw all seem to use very similar firmware.
