### ISSUE TITLE
HP Color Laserjet MFP m178-m181

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#13]
I think this device can join those that work with sane-airscan.

Regards,

Brian.

**Comment by debiantriage** [comment]
See [https://bugs.launchpad.net/hplip/+bug/1863316](url)

**Comment by alexpevzner** [comment]
README.md updated. Thanks a lot, Brian!

**Comment by debiantriage** [comment]
I formatted the link to the original bug report incorrectly. Below should be correct.

https://bugs.launchpad.net/hplip/+bug/1863316

I also named the device incorrectly and put _LaserJet_ instead of _Laser_.

> ty=HP Color Laser MFP 178 179
