### ISSUE TITLE
Port needed in Host header for some scanners

### ISSUE THREAD

**Issue by yetamrra** [alexpevzner/sane-airscan#136]
We have a report from Epson that some of their models require the port to be included in the Host header for eSCL even if it matches the default value.  When the port isn't included, the steps up to the scan job creation work, but an invalid redirect will be sent from the response to /eSCL/ScanJobs and then the scan job will never finish.

I saw from the commit history that unconditionally adding the port to the Host header will break other devices.  Do you think this could be added as a quirk for just Epson devices?  They have confirmed to us that all their models will work correctly if the port is present, so it shouldn't introduce any new compatibility breaks.  I'm happy to take a stab at adding a quirk if you think that's a viable approach.

**Comment by alexpevzner** [comment]
Yes, it sounds reasonable. If Epson people can be 100% sure that all Epson devices will work with such a quirk, we can apply this quirk to all Epson devices.

**Comment by yetamrra** [comment]
OK, I'll put something together and send a PR in a few days.

**Comment by alexpevzner** [comment]
OK, agreed.
