### ISSUE TITLE
DELL C3765dnf works perfectly

### ISSUE THREAD

**Issue by kecksk0enig** [alexpevzner/sane-airscan#151]
Hi! just wanted to inform you that the Scanner works perfectly with sane-airscan. ADF and so on works perfect.
Thanks for your work!

If you need any more specific information about the model or which mode (escl or wsd) it is working pleas feel free to respond. I'll be happy to add missing information here.

**Comment by alexpevzner** [comment]
Show me an output of `scanimage -L`, please. It will let me to guess, what protocol is in use, eSCL or WSD

**Comment by kecksk0enig** [comment]
$  scanimage -L
device `airscan:w0:Dell C3765dnf Color MFP (BC:D7:B9)' is a WSD Dell C3765dnf Color MFP (BC:D7:B9) ip=192.168.178.84

**Comment by alexpevzner** [comment]
Thanks!
