### ISSUE TITLE
Canon MG5300 forward to PC

### ISSUE THREAD

**Issue by malloy139** [alexpevzner/sane-airscan#158]
Hello,

i'm not sure if this project is intended to do this. I thought installing this enables to scan directly on the device and forward it to the PC and store the file somewhere. But the PC is not found by the scanner.
Btw. airscan-discover ans scanimage -L works fine

**Comment by alexpevzner** [comment]
Supporting push-mode scan (when transfer is initiated by device, not by PC) is out of the scope of this project.
