### ISSUE TITLE
Interop with SimulPiscator/AirSane fails

### ISSUE THREAD

**Issue by markosjal** [alexpevzner/sane-airscan#171]
Just FYI , testing interoperability with alexpevzner/sane-airscan Multi Page scanning from ADF fails.

Please see attached wireshark pcap . Sorry because it is a 'localhost' connection it can be hard to follow (same IP to/from Same IP)

At packet number 1031 you see "409 Unknown Reason" . I believe that is the point where it all falls apart in Document scanner 3.36.3

This was tested on a new install of Linux Mint 20.2 Uma base: Ubuntu 20.04 focal.

The capture file is here
http://portlandtel.com/pcap/eSCLFailpcapng.zip

Bug report for SimulPiscator/AirSane is here https://github.com/SimulPiscator/AirSane/issues/76

**Comment by alexpevzner** [comment]
Looks line no action is required from my side...
