### ISSUE TITLE
Verified as supported: Canon MG5370

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#173]
https://askubuntu.com/questions/1361282/how-to-setup-canon-mg5370-printer-scanner-in-ubuntu-20-04

> $ scanimage -L
device `pixma:04A91754_20EE62' is a CANON Canon PIXMA MG5300 multi-function peripheral
device `airscan:w1:Canon MG5300 series' is a WSD Canon MG5300 series ip=192.168.1.XXX

**Comment by alexpevzner** [comment]
Added -- thanks!
