### ISSUE TITLE
Verified as supported: Brother MFC-J1300DW.

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#177]
ty=Brother MFC-J1300DW

> device `airscan:e0:Brother MFC-J1300DW' is a eSCL Brother MFC-J1300DW ip=192.168.178.49

Works with platen and ADF.

https://forums.linuxmint.com/viewtopic.php?f=51&t=357615&sid=d83d0b3424311b1080d01530f08ccb62

**Comment by alexpevzner** [comment]
Added -- thanks!
