### ISSUE TITLE
Verifies as supported: Epson ET-2760 

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#178]
https://ubuntuforums.org/showthread.php?t=2466234

> minilek@minilek-laptop:~$ scanimage -L
device `airscan:e0:EPSON ET-2760 Series' is a eSCL EPSON ET-2760 Series ip=192.168.86.20

> [devices]
EPSON ET-2760 Series = http://192.168.86.207:443/eSCL/, eSCL
EPSON ET-2760 Series = https://192.168.86.207:443/eSCL/, eSCL
EPSON ET-2760 Series = http://192.168.86.207:80/WDP/SCAN, WSD
EPSON ET-2760 Series = http://[fe80::decd:2fff:fe4a:3aab%253]:80/WDP/SCAN, WSD
minilek@minilek-laptop:~$

**Comment by alexpevzner** [comment]
Added - thanks!
