### ISSUE TITLE
DCP-L2540DW stops at 300 dpi

### ISSUE THREAD

**Issue by espindola** [alexpevzner/sane-airscan#183]
With the brother provide driver, scanimage -A prints

--resolution 100|150|200|300|400|600|1200|2400|4800|9600dpi [200]

With airscan I get

--resolution 100|200|300dpi [300]

**Comment by alexpevzner** [comment]
Yes, some devices provide more functionality via their proprietary driver that they expose via eSCL/WSD protocols. Here I cannot do anything, sorry.
