### ISSUE TITLE
Verified as supported: Lexmark MC3326adwe

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#187]
https://answers.launchpad.net/hplip/+question/699033

The relevant messages are 19, 20, 21 and 22.

> John@john-H81M-S2H-GSM:~$ scanimage -L 
device `airscan:e0:Lexmark MC3326adwe' is a eSCL Lexmark C3326adwe ip=192.168.1.75
 device `airscan:e1:Lexmark MC3326adwe (USB)' is a eSCL Lexmark C3326adwe (USB) ip=127.0.0.1
Now xsane finds two devices and I am able to scan using the flatbed and the ADF!

I think that `airscan:eN:<ip_address>` and `airscan:wN :<ip_address>` are valid URI formats. Am I correct? If so, how do I determine the value of N?

**Comment by Htegu** [comment]
GGGGGGGGGHZDGFVCGFCVCGXFDfsfsfs6fyftye5ee5d4323##%#%FGIGHytRFtffdrdedyt
