### ISSUE TITLE
canon pixma ts3450 works

### ISSUE THREAD

**Issue by phil170** [alexpevzner/sane-airscan#202]
Hey,
just wanted to inform you that sane-airplay works perfectly with Canon Pixma TS3450 for me!
Awesome work!
If you need more info, hit me up!
Cheers, 
Phil.

**Comment by alexpevzner** [comment]
Hi!

could you please tell me, what `scanimage -L` prints, so I will know what protocol (eSCL or WSD) is actually used?

**Comment by phil170** [comment]
Hey,
this is the output:

device escl:https://192.168.0.30:443' is a Canon TS3400 series platen scanner
device airscan:e0:Canon TS3400 series' is a eSCL Canon TS3400 series ip=192.168.0.30

**Comment by alexpevzner** [comment]
Thanks a lot!
