### ISSUE TITLE
Brother MFC-L8650CDW

### ISSUE THREAD

**Issue by shadyslim2018** [alexpevzner/sane-airscan#223]
airscan has detected Brother MFC-L8650CDW and using WSD protocol, however,  I'm unable to do duplex scanning. Is there a way I can manually allow the duplex scanning?

**Comment by alexpevzner** [comment]
Hi @shadyslim2018,

sorry for **very** long delay in response. Is this issue still relevant?

**Comment by shadyslim2018** [comment]
I think so. I think it was just a hidden configuration. You can close this ticket, thanks.
