### ISSUE TITLE
Kyocera ECOSYS M2035dn FS-1035MFP/DP is Work

### ISSUE THREAD

**Issue by Krakozyabrik** [alexpevzner/sane-airscan#234]
Add to list
Kyocera ECOSYS M2035dn eSCL- no WSD - yes4
FS-1035MFP/DP eSCL- no WSD - yes4

[4]: this device requires manual action on its front panel to initiate WSD scan: Send->WSD Scan->From Computer

**Comment by alexpevzner** [comment]
It's probably a variant of my ECOSYS M2040dn with the same firmware, but slightly different printing unit (slower and uses smaller toner cartridge).

Tbanks!

**Comment by Krakozyabrik** [comment]
No, this is an older model that does not support the AirScan or AirPrint protocol
