### ISSUE TITLE
Missing i386 builds

### ISSUE THREAD

**Issue by tux-mind** [alexpevzner/sane-airscan#235]
Hey, thank you for this great tool and for contributing to FOSS :)

I didn't find an i386 build on your ubuntu packages repo, it would be nice to have them for some users that might have some old PC around.

Thank you again :)

**Comment by alexpevzner** [comment]
Fixed. There were some problems with i386 builds at OpenSUSE build services for newer distros, so I guessed that OpenSUSE cancelled  i386 support for these distros and disabled these builds. But now tried to enable, and everything works.

Built packages will propagate to the appropriate download repos. Usually it takes from few minutes to few hours, depending on a weather on a SUSE side :-)

Enjoy!
