### ISSUE TITLE
Verified as supported: HP Neverstop Laser MFP 1202nw

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#244]
https://answers.launchpad.net/hplip/+question/702354

> ty=HP Neverstop Laser MFP 120x

> f@f-Falco:~$ scanimage -L
device `airscan:e0:HP Neverstop Laser MFP 1202nw (ABCCA8) (USB)' is a eSCL HP Neverstop Laser MFP 1202nw (ABCCA8) (USB) ip=127.0.0.1

> f@f-Falco:~$ airscan-discover
[devices]
HP Neverstop Laser MFP 1202nw (ABCCA8) (USB) = http://127.0.0.1:60000/eSCL/, eSCL

> YES, i get scanning! Not only with simple scan but also with Xsane.

Alex,

Your provision of packages (ipp-usb and sane-airscan) via the SUSE build service is a winner!

Brian.

**Comment by alexpevzner** [comment]
Thanks, Brian!
