### ISSUE TITLE
Compression Artifacts

### ISSUE THREAD

**Issue by bjoernf77** [alexpevzner/sane-airscan#250]
Hi,

I just tried to scan under Linux Mint 20.3 with my HP Color LaserJet Pro MFP M479fdw using xsane and GIMP (I also tried some other combinations), but it seems that I cannot get uncompressed high quality data from my scanner, only always some compression on top. After a discussion on launchpad (https://answers.launchpad.net/hplip/+question/702688) I now found the attached log file and have seen, that the scanner indeed provides more options, but that they are not really available/used (another one would be line art or black and white). I think what would be needed is "<pwg:DocumentFormat>application/octet-stream</pwg:DocumentFormat>" instead of jpeg or pdf, then I think it would also be uncompressed ...(?)
If that's not how it would/should work, is there any other way to get uncompressed high quality data from my scanner under Linux. I just double checked on a Windows computer with the Fax and Scan tool, which did the job without a problem, so at least it's not a Hardware issue.

Thx
Björn

[xsane-HP-Color-LaserJet-Pro-M478f-9f-[835929].log](https://github.com/alexpevzner/sane-airscan/files/9298710/xsane-HP-Color-LaserJet-Pro-M478f-9f-.835929.log)
[xsane-HP-Color-LaserJet-Pro-M478f-9f-[835929].zip](https://github.com/alexpevzner/sane-airscan/files/9298717/xsane-HP-Color-LaserJet-Pro-M478f-9f-.835929.zip)

**Comment by alexpevzner** [comment]
Hi @bjoernf77,

sorry for long delay with reply. Do you know that according to your log, you scan with resolution 75 DPI?
