### ISSUE TITLE
HP ScanJet Pro 2000 s2: confirmed to work.

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#254]
It is nice to find some USB-only devices working with ipp-usb.

> This is an edited `scanimage -L`:
device `airscan:e0:HP ScanJet Pro 2000 s2 (USB)' is a eSCL HP ScanJet Pro 2000

> airscan-discover
[devices]
  HP ScanJet Pro 2000 s2 (USB) = http://127.0.0.1:60000/eSCL/, eSCL

**Comment by alexpevzner** [comment]
> It is nice to find some USB-only devices working with ipp-usb.

Really nice, thanks!
