### ISSUE TITLE
Support for "Scan to PC"

### ISSUE THREAD

**Issue by jerome-pouiller** [alexpevzner/sane-airscan#261]
On my scanner (a Samsung CLX-3305), it is possible to "Scan to WDS". When I select that, my Windows workstation is listed, but obviously, my Linux does not appear.

Unfortunately, I didn't find so much information about this protocol and even less about its support under Linux. I assume I need to advertise my Linux in some way. I have tested [`wsdd2`][https://github.com/Andy2244/wsdd2] without success.

If necessary, I think I can capture the network data exchanged between my scanner and my Windows.

**Comment by alexpevzner** [comment]
Hi Jérôme,

implementing "Scan to PC" (push scan) requires a lot of work. At least:
* WSD advertiser, so printer will see your PC
* some specialised HTTP server on PC side, that will allow printer to connect to PC to initiate scan
* firewall integration, so firewall will not block this server
* desktop integration, which will trigger some pop-up window at PC side when printer wants to scan
* some PC-side application, able to catch pictures and save them on PC

This all is very far out of scope of this project

**Comment by tobiasBora** [comment]
I was also very much interested in this feature to scan automatically to a NAS. I tried to configure wsdd (hard to know if I did it well), but my linux does not appear in the list of PC on the Canon. So do you confirm that the WSD for push-scan is different from the WSD used to share file? Any pointer to an official documentation of the spec of the scan-version ?

**Comment by Tomblarom** [comment]
That's a huge bummer, that nothing like this exists. I have an Epson ET-4950, that also features "Scan-to-WSD", but I wasn't even able to attach the printer to my Windows 10 machine for testing, [using the manual](https://download4.epson.biz/sec_pubs/et-4950_series/useg/en/GUID-0C65018F-2F83-47AC-8763-E50777BAB3DF.htm). It appears to be for Windows 7 and does not show up under Network, as seen in the screenshot.
