### ISSUE TITLE
Canon MF240 Series: Confirmed working with eSCL

### ISSUE THREAD

**Issue by drvox1600** [alexpevzner/sane-airscan#262]
Works when "PrinterName" = http://yourprinterip/eSCL is added to the [devices] section of /etc/sane.d/airscan.conf

No port number was needed.

mDNS and AirPrint enabled in printer web console.

Tested on RHEL 9.0 x86_64, confirmed working with xsane and skanlite

**Comment by alexpevzner** [comment]
Hi @drvox1600,

sorry for **very** long delay with response.

MF240 already known to work in the WSD mode, though WSD Scanning is disabled by default on this device and needs to be manually enabled.

Does your message means, that eSCL works too, but automatic discovery of eSCL doesn't work?
