### ISSUE TITLE
Brother MFC-J470DW Confirmed to work

### ISSUE THREAD

**Issue by exaCORE42** [alexpevzner/sane-airscan#266]
> device `airscan:w1:Brother MFC-J470DW' is a WSD Brother MFC-J470DW ip=

is the result I get when using the command  `scanimage -L` (I removed the IP for privacy reasons)

Also, the printer scans correctly (if that is useful information).

**Comment by alexpevzner** [comment]
Hi @exaCORE42,

actually, this device already known to work. But anyway, thank you for feedback!
