### ISSUE TITLE
Could airscan-discover find the ipp-over-usb scanner

### ISSUE THREAD

**Issue by tangyanli** [alexpevzner/sane-airscan#27]
Hi,
I have a multi-functional printer which supports ipp-over-usb function, and the printer has inside scanner.
When I plug the printer into USB port and set the airprint = on, I can send data to the printer by IPP URI. And when I try to set the airscan.conf as below, the airscan scan the picture well.
***
[devices]
My Scanner = http://127.0.0.1:60000/eSCL
***

But when I use the airscan-discover tool to find the supported scanner, the tool cannot output the ipp-on-usb scanner information.
Is there some method to discover the ipp-on-usb scanner information?

**Comment by alexpevzner** [comment]
Hi,
what is your Linux distro? And what ippusbxd version do you use?

**Comment by tangyanli** [comment]
Debian 10 + ippusbxd_1.34-2

**Comment by tangyanli** [comment]
Ubuntu20.04 + ippusbxd_1.34-2 has the same phenomenon.

**Comment by alexpevzner** [comment]
Please, show me output of the following command:

    avahi-browse -rt -a

For now let it be on Ubuntu

**Comment by tangyanli** [comment]
Hi,
When I output the "avahi-browse -rt -a" information, I found the phenomenon has a little difference with yesterday.
When I startup Ubuntu with network cable plugging in, the airscan-discover can find the ipp-over-usb infor; but when I reboot Ubuntu without network cable plugging in, the airscan-discover cannot output the ipp-over-usb infor.

The attachment file is output information for "avahi-browse -rt -a" and "airscan-discover -d"

[Startup_Ubuntu_withNetworkCable.log](https://github.com/alexpevzner/sane-airscan/files/4631786/Startup_Ubuntu_withNetworkCable.log)
[Startup_Ubuntu_withoutNetworkCable.log](https://github.com/alexpevzner/sane-airscan/files/4631787/Startup_Ubuntu_withoutNetworkCable.log)

**Comment by alexpevzner** [comment]
Hi,

on Ububtu, the problem seems to be in ippusbxd. I'll investigate it better and will contact you a bit later.

On Debian, there is additional problem with the old version on Avahi. It is explained on ippusbxd README: https://github.com/OpenPrinting/ippusbxd

**Comment by tangyanli** [comment]
PPS:
Actually, On Debian, the Avahi is the newest version: avahi-daemon_0.8-1_xx.deb

**Comment by alexpevzner** [comment]
Hi,

may I ask you to try to replace ippusbxd with the alternative package:
https://github.com/OpenPrinting/ipp-usb

You probably need to do the following:
1. Install Go compiler
2. Clone and enter https://github.com/OpenPrinting/ipp-usb directory
3. make
4. Uninstall ippusbxd
5. As root, call make install in the ipp-usb directory
7. Unplug and plug back USB cable, or reboot, whatever is simpler

**Comment by tangyanli** [comment]
OK，I will test the ipp-usb next week.

**Comment by tangyanli** [comment]
Hi,
I failed to build the ipp-usb.

Error info: go: github.com/OpenPrinting/goipp@v0.0.0-20200517195333-da79ff13b3a4: Get "https://proxy.golang.org/github.com/%21open%21printing/goipp/@v/v0.0.0-20200517195333-da79ff13b3a4.mod": dial tcp 172.217.160.113:443: connect: connection refused

I cann't access the 172.217.160.113:443. Does the server still exist now?

**Comment by alexpevzner** [comment]
This is Google's server. Probably, some temporary error, or may be some restrictive firewall between you and Google, please try again.

If you will succeed, you actually can try to run it directly from build directory, without installation.

If not, wait a little bit, I'll create ipp-usb binary packages.

**Comment by tangyanli** [comment]
I tried many times. So the binary packages would be better.

**Comment by alexpevzner** [comment]
OK. At this case it will be tomorrow. I'll let you know.

**Comment by tangyanli** [comment]
Hi,
I have build the ipp-usb.
TestOS: Ubuntu20.04

For ippusbxd:
Unplug and plug back USB cable ten times, every time the IPP is advertised, but the eSCL is only advertised 3 times.

For ipp-usb (set mode = standalone):
Also unplug and plug back USB cable ten times,  every time the IPP and eSCL are both advertised.

**Comment by alexpevzner** [comment]
Hi,
the packages for ipp-usb are here: https://download.opensuse.org/repositories/home:/pzz/

**Comment by tangyanli** [comment]
Got it.
Test result was reported yesterday. Please refer the previous comment.

**Comment by tangyanli** [comment]
Hi,
The ipp-usb works really fine.
And may I ask your help to support ARM binary version?

**Comment by tangyanli** [comment]
Hi,
This is just a information.
I compiled the airscan and ipp-usb on a ARM PC.
They all work fine.
Thanks.

**Comment by alexpevzner** [comment]
ARM binaries for what distro?

**Comment by tangyanli** [comment]
Chinese Linux distro, deepin

**Comment by alexpevzner** [comment]
@tangyanli,

For binary packaging, I use OpenSUSE build services, which support packaging for many (but not all) Linux targets,

This is a more or less accurate list of targets, supported by OpenSUSE build services: https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets

If Deepin is compatible with one of listed distros and it has ARM target, I can enable it.

Alternatively, if Deepin provides packaging for user-supplied software (as many other distros do), you can try to add ipp-usb there by yourself. It should not be very difficult, an I can assist you doing this in a case of any problems (in assumption that I don't read Chinese :-)). If we will go this way, once we succeed, I can add a reference from the ipp-usb README to your 3rd party repo.

**Comment by tangyanli** [comment]
That’s so great!
Deepin is compatible with Debian.
Does the OpenSUSE build services support MIPS target based on Debian?

**Comment by alexpevzner** [comment]
For Debian 10 the list is following:
* i586
* x86_64
* ppc
* ppc64
* s390x
* local
* armv6l
* armv7l
* aarch64
* ppc64le
* aarch64_ilp32
* riscv64

So unfortunately, no MIPS.

Go compiler, however, supports MIPS, so outside of SuSE, compilation for MIPS should be possible

**Comment by tangyanli** [comment]
What a pity.
From now on, I will build MIPS version.
I may ask your help again :-)

**Comment by alexpevzner** [comment]
OK. I think, for now I can close sane-airscan issue, as resolved. If you will have some more questions, you may open a new issue.

ipp-usb is hosted here: https://github.com/OpenPrinting/ipp-usb

**Comment by tangyanli** [comment]
All right. Thank you so much!

**Comment by alexpevzner** [comment]
You are always welcome!
