### ISSUE TITLE
Xerox B215 WSD compatibility

### ISSUE THREAD

**Issue by agapovmax** [alexpevzner/sane-airscan#294]
Please add Xerox B215 to[ Compatibility list](https://github.com/alexpevzner/sane-airscan#compatibility) with WSD-mode. Scan work perfectly, without manual action on device front panel.
WSD option needs to be enabled on web-console.

**Comment by alexpevzner** [comment]
Hi @agapovmax,

Xerox B215 already known to support eSCL. Do I hear you correctly: you want to update the description by adding WSD?

> WSD option needs to be enabled on web-console.

I probably need a short instruction how to do it, to add it into foot notes.

**Comment by agapovmax** [comment]
Yes, correctly. 
Properties>Connectivity>Protocols>WSD
![B215](https://github.com/alexpevzner/sane-airscan/assets/16970072/86c2fb26-704a-420d-a785-e592f7cfbe5a)

**Comment by alexpevzner** [comment]
Thanks!
