### ISSUE TITLE
HP LaserJet MFP M139-M142: confirmed to work with eSCL

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#297]
https://forums.linuxmint.com/viewtopic.php?t=401515

The device is an HP LaserJet MFP M140w, first sold 2022.

> scanimage -L
device `escl:[https://192.168.1.8:443](https://192.168.1.8/)' is a HP LaserJet MFP M140w (2E855D) platen scanner
device `hpaio:/net/hp_laserjet_mfp_m139-m142?ip=192.168.1.8&queue=false' is a Hewlett-Packard hp_laserjet_mfp_m139-m142 all-in-one
device `airscan:e0:HP LaserJet MFP M140w (2E855D)' is a eSCL HP LaserJet MFP M140w (2E855D) ip=192.168.1.8,
2a01:827:1922:e401:7e57:58ff:fe2e:855d

> airscan-discover
[devices]
HP LaserJet MFP M140w (2E855D) = http://192.168.1.8:8080/eSCL/, eSCL
HP LaserJet MFP M140w (2E855D) = [https://192.168.1.8:443/eSCL/](https://192.168.1.8/eSCL/), eSCL
HP LaserJet MFP M140w (2E855D) = http://[2a01:827:1922:e401:7e57:58ff:fe2e:855d]:53048/, WSD
HP LaserJet MFP M140w (2E855D) = http://[fd31:8e82:6795:1:7e57:58ff:fe2e:855d]:53048/, WSD
HP LaserJet MFP M140w (2E855D) = http://192.168.1.8:53048/, WSD
HP LaserJet MFP M140w (2E855D) = http://[fe80::7e57:58ff:fe2e:855d%252]:53048/, WSD

**Comment by alexpevzner** [comment]
Thanks!
