### ISSUE TITLE
Another four working devices

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#30]
HP OfficeJet 3830 series
https://answers.launchpad.net/hplip/+question/690723

Lexmark International Lexmark MC2535adwe
Canon Pixma MG7750
HP MFP477fdw (HP Colour LaserJet Pro MFP M477 series?)
https://forums.linuxmint.com/viewtopic.php?f=51&t=320064

Cheers,

Brian.

**Comment by alexpevzner** [comment]
Thank a lot!

Now if device is not shown with avahi-browse -rt _uscan._tcp, it doesn't mean it is not supported:
1. Some devices advertise only _uscans._tcp (HTTPS version of the protocol). Some (all?) Xerox, for example
2. There are WSD devices without eSCL

The simplest way to check for now is `airscan-discover`
