### ISSUE TITLE
EPSON DS-780N missing Lineart mode

### ISSUE THREAD

**Issue by stephenjamieson** [alexpevzner/sane-airscan#306]
I am not sure if this is an issue with sane-airscan or something with epson's WSD implementation, however scanimage is not showing that the Lineart mode is available, and it is also only showing two resolutions.   This scanner has 75-1200 dpi available along with black and white scanning.  It also has options for skipping blank pages, correcting document skew, enhancing text etc (though again WSD probably doesn't implement all of these extras).

```bash
scanimage -A
Output format is not set, using pnm as a default.

All options specific to device `airscan:w0:EPSON DS-780N':
  Standard:
    --resolution 100|300dpi [300]
        Sets the resolution of the scanned image.
    --mode Color|Gray [Color]
        Selects the scan mode (e.g., lineart, monochrome, or color).
    --source ADF|ADF Duplex [ADF]
        Selects the scan source (such as a document-feeder).
  Geometry:
    -l 0..215.9mm [0]
        Top-left x position of scan area.
    -t 0..393.7mm [0]
        Top-left y position of scan area.
    -x 0..215.9mm [215.9]
        Width of scan-area.
    -y 0..393.7mm [393.7]
        Height of scan-area.
  Enhancement:
    --brightness -100..100% (in steps of 1) [0]
        Controls the brightness of the acquired image.
    --contrast -100..100% (in steps of 1) [0]
        Controls the contrast of the acquired image.
    --shadow 0..100% (in steps of 1) [0]
        Selects what radiance level should be considered "black".
    --highlight 0..100% (in steps of 1) [100]
        Selects what radiance level should be considered "white".
    --analog-gamma 0.0999908..4 [1]
        Analog gamma-correction
    --negative[=(yes|no)] [no]
        Swap black and white
    --adf-justification-x <string> [inactive]
        ADF width justification (left/right/center)
    --adf-justification-y <string> [inactive]
        ADF height justification (top/bottom/center)
```

```bash
scanimage -L
device `airscan:w0:EPSON DS-780N' is a WSD EPSON DS-780N ip=192.168.22.3
```

**Comment by alexpevzner** [comment]
Hi @stephenjamieson,

Missed lineart mode - this is by design. Implementing this mode adds many complexity to image decoding. And any image can be easily converted to lineart at host, so why bother with implementing this mode in the driver? (correct me, if I wrong).

Regarding resolutions, some devices doesn't expose full range of supported resolutions via driverless protocols (i.e., eSCL and WSD), while still supporting them in proprietary drivers.

So this is unlikely that something can be improved at this case...
