### ISSUE TITLE
Canon MF264dw, works with airscan, but limits resolution to 300dpi

### ISSUE THREAD

**Issue by TooManyHobbies** [alexpevzner/sane-airscan#336]
Hi,

I have a Canon MF264dw. When I choose the airscan/eSCL from the devices list, the scan works, but at a maximum of 300dpi. If I choose the pixma entry, I can choose the 600 dpi option, but no matter what resolution I choose, I get the error: "Error during device I/O" reported through my front end Skanlite. My scanner is connected via ethernet on my lan.

Here is the output of scanimage -L
device v4l:/dev/video0' is a Noname Integrated Camera: Integrated C virtual device device pixma:MF260_Canon58871c' is a CANON Canon i-SENSYS MF260 Series multi-function peripheral
device `airscan:e0:Canon MF260' is a eSCL Canon MF260 ip=192.168.1.120

My OS is Garuda Linux (Arch basically)
uname -a
Linux Legion5 6.8.7-zen1-1-zen [#1 (closed)](https://github.com/sane-project/backends/-/issues/1) ZEN SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:00 +0000 x86_64 GNU/Linux

Any help is greatly appreciated.  I also opened the issue on the SANE gitlab page, but then realized that air-scan had it's own page. Sorry for the duplication. Thank you.

**Comment by alexpevzner** [comment]
Hi @TooManyHobbies,

this is quite common for devices not to expose their full functionality (such as high DPI) via driverless interfaces, like eSCL or WSD.

So 300 DPI is the device limitation, not the driver limitation. `sane-airscan` quires device capabilities from the device and relies on returned values. There is not built-in limitation in the driver.

The `pixma` driver uses reverse-engeneered Canon proprietary protocol, so for some devices it may offer more functionality that `sane-airscan`. But for some other devices it may recognize the device but fail to work at all, as in your case.

You probably should send issues related to the `pixma` backend to the SANE gitlab page, and they often (but not always) able to help.

Alternatively, you can use [sane-devel](https://alioth-lists.debian.net/cgi-bin/mailman/listinfo/sane-devel) mail list; SANE developers often help users with solving their problems.
