### ISSUE TITLE
ESCL Load Delay workaround for Brother brothers causes speed regression

### ISSUE THREAD

**Issue by fabled** [alexpevzner/sane-airscan#347]
I have a HP Color LaserJet Entrprise Flow MFP X677 device which can scan up to 100 pages per minute (in duplex mode this means 200 scanned images per minute).

The Brother printer specific Load Delay logic typically issues 100-500ms delay on this printer purely due to the time it takes to transfer one image. Given the fast scanning speeds, this roughly halves the scanning speed.

Could this printer vendor/model specific workaround be made a kludge that triggers only if a faulty printer is detected?

The commit adding this code is at 3475ee5975bbebf2b5695a30ebb653d53a7fb6d3 and the original issue is #39

**Comment by alexpevzner** [comment]
Well, hope the initial problem was Brother-specific and I didn't broke any non-Brother devices that actually depend on this delay, but I'm not aware of that fact...
