### ISSUE TITLE
Two working HP devices

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#35]

**Comment by debiantriage** [comment]
https://forums.linuxmint.com/viewtopic.php?f=51&t=321399&sid=b250bffa03239c0525c00c100b2890f7&start=20

Your ipp-usb package provision came in useful in this thread.

> ~$ scanimage -L
device `airscan:e0:HP ENVY Pro 6400 series [B2FB97] (USB)' is a eSCL HP ENVY Pro 6400 series [B2FB97] (USB) eSCL network scanner

https://bugs.launchpad.net/hplip/+bug/1882390

> $ scanimage -L
device `airscan:e0:HP040E3C60A8A2 (HP Laser MFP 131 133 135-138)' is a eSCL HP040E3C60A8A2 (HP Laser MFP 131 133 135-138) eSCL network scanner

An unusual device. Does not use HPLIP. 

Cheers,

Brian.

**Comment by alexpevzner** [comment]
Thank a lot!
