### ISSUE TITLE
HP Color LaserJet MFP M281fdw

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#4]
>    device `airscan:HP Color LaserJet MFP M281fdw (C23F2C)' is a AirScan HP Color LaserJet MFP M281fdw (C23F2C) eSCL network scanner

https://forums.linuxmint.com/viewtopic.php?f=51&t=309086

**Comment by alexpevzner** [comment]
@debiantriage, it's not quite clear, what action is required here from me. Device seems to work, correct?

**Comment by debiantriage** [comment]
On Fri 10 Jan 2020 at 13:12:50 -0800, Alexander Pevzner wrote:

> @debiantriage, it's not quite clear, what action is required here
> from me. Device seems to work, correct?

Indeed, the user reports the device as working. I guess the report
needn't remain open.

Cheers,

Brian.

**Comment by alexpevzner** [comment]
OK, thank you, @debiantriage 

Seems that some users experience certain difficulties installing the driver. May be, I should somehow clarify the documentation, how do you think?

**Comment by debiantriage** [comment]
On Sat 11 Jan 2020 at 12:57:56 -0800, Alexander Pevzner wrote:

> OK, thank you, @debiantriage 
> 
> Seems that some users experience certain difficulties installing the
> driver. May be, I should somehow clarify the documentation, how do
> you think?

Some users will always have difficulties, even when given full
instructions. Your docs are fine.

Cheers,

Brian.
