### ISSUE TITLE
How can i disable sane-airscan?

### ISSUE THREAD

**Issue by Kowa92** [alexpevzner/sane-airscan#47]
Hi,
i wanted to know how i could do to disable this backend when i run the `saneairscan -L` command. Is there an option in his config file?
Also, how can i uninstall this package once i have compiled using the binaries with `make install`?
Thanks.

**Comment by alexpevzner** [comment]
On 6/29/20 9:14 PM, Kowa92 wrote:

> i wanted to know how i could do to disable this backend when i run the 
> |saneairscan -L| command. Is there an option in his config file?

Comment out (with the # character) the airscan line in the 
/etc/sane.d/dll.d/airscan file

> Also, how can i uninstall this package once i have compiled using the 
> binaries with |make install|?

I've just added |make uninstal| -- use with care :-)

Note, it intentionally leaves the /etc/sane.d/airscan.conf file, so you 
will have to remove it manually, if you don't need it anymore.

-- 

	Wishes, Alexander Pevzner (pzz@apevzner.com)

**Comment by Kowa92** [comment]
Great! :)

> I've just added |make uninstal| -- use with care :-) Note, it intentionally leaves the /etc/sane.d/airscan.conf file, so you will have to remove it manually, if you don't need it anymore.

It starts from 0.99.8 version of sane-airscan, right?

**Comment by alexpevzner** [comment]
No, it will start from not yet released 0.99.9. But if you build from sources, just upgrade sources, and `make uninstall` will work (if you use precompiled binary packages, you can always uninstall, using your package manager)

**Comment by alexpevzner** [comment]
BTW, what is wrong with sane-airscan, so disabling and uninstalling it is a major feature for you? :-)

**Comment by Kowa92** [comment]
> No, it will start from not yet released 0.99.9. But if you build from sources, just upgrade sources, and `make uninstall` will work (if you use precompiled binary packages, you can always uninstall, using your package manager)

Ok, which is the command for upgrade sources using git? (I don't know git well.. sry)

Unfortunately, i cannot use precompiled binary packages because i installed sane-airscan on RaspberryPi..

**Comment by Kowa92** [comment]
> BTW, what is wrong with sane-airscan, so disabling and uninstalling it is a major feature for you? :-)

There is nothing wrong .. I simply don't want to have one driver the next day for a single device (they could be confusing) :)

**Comment by alexpevzner** [comment]
`git pull`

I've added Debian 10/armv7 build. Is it enough for Raspberry Pi?

**Comment by Kowa92** [comment]
You have just added it! :O Some days ago there wasn't an  _armhf.deb package! :)

Good work man! Thanks for all! ^^

**Comment by alexpevzner** [comment]
I've also added Raspbian 9 and 10. Have no idea what is better for Raspberry.

There are a lot of targets I can add at OBS, but I don't want to overload their build servers without need, so among obviously popular targets, I'm adding others on demand.

**Comment by Kowa92** [comment]
What do you mean with OBS?

**Comment by alexpevzner** [comment]
SUSE Open Build. Service

сб, 4 июл. 2020 г., 13:01 Kowa92 <notifications@github.com>:
