### ISSUE TITLE
Как сам сканер в систему то установить?

### ISSUE THREAD

**Issue by marckt** [alexpevzner/sane-airscan#50]
Ubuntu 18.04
Kyocera m2040dn
deb пакет с сайта киосеры ставлю. Принтер печатает сканера нет
airscan-discover -d `MDNS: browse/ipv4 "Kyocera ECOSYS M2040dn KPDL`
scanimage -L ничего

**Comment by alexpevzner** [comment]
Давайте по-порядку. Что говорит `airscan-discover` без -d?

**Comment by marckt** [comment]
Ничего не выдает.
airscan-discover
`[devices]
`

**Comment by alexpevzner** [comment]
А принтер подключен по сети или через USB?

**Comment by marckt** [comment]
Подключен по сети

**Comment by alexpevzner** [comment]
`avahi-browse -rt _uscan._tcp` его видит?

**Comment by alexpevzner** [comment]
Скажите пожалуйста, эта проблема еще актуальна, или можно закрыть тикет?

**Comment by marckt** [comment]
Настроил, сканирование в sbm папку через функционал МФУ. Так даже проще
Спасибо, неактуально можно закрыть
