### ISSUE TITLE
build system issues

### ISSUE THREAD

**Issue by andyrtr** [alexpevzner/sane-airscan#53]
What's the preferred way to build sane-airscan - the simple Makefile or the meson based build?

The Makefile doesn't create the symlink libsane-airscan.so -> libsane-airscan.so.1 and doesn't seem to respect our LDFLAGS properly leaving unneeded dependencies linked into it.
sane-airscan W: Unused shared library '/usr/lib/libjpeg.so.8' by file ('usr/bin/airscan-discover')

The Meson based build doesn't allow to pass SYSCONFDIR and puts config them under /usr/etc, it doesn't split dll.d/airscan to the dll.d directory. Meson system seems to honor our LDFLAGS.

**Comment by alexpevzner** [comment]
The official way is `Makefile`. Meson build was contributed by my users, and I simply keep it here, trying not to break it ocassionally.

I can add symlink creation, but I have a strong impression that it actually is not needed for any purpose.

I will look how to remove libjpeg and libpng from airscan-discover dependencies

**Comment by alexpevzner** [comment]
`Makefile` updated, so `airscan-discover` is not linked against jpeg/png libraries anymore

**Comment by leigh123linux** [comment]
> The official way is `Makefile`. Meson build was contributed by my users, and I simply keep it here, trying not to break it ocassionally.

This Pr should address the meson build https://github.com/alexpevzner/sane-airscan/pull/58

**Comment by alexpevzner** [comment]
Closed - fixed
