### ISSUE TITLE
Canon MF642cdw. HP LaserJet M28a MFP. Epson ET-2750.

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#59]
https://forums.linuxmint.com/viewtopic.php?f=51&t=322031

> ty=Canon MF642C/643C/644C

No response (as yet) to two requests for `scanimage -L`.

https://answers.launchpad.net/hplip/+question/692155

> ty=HP LaserJet MFP M28a

This is a USB-only device. It has given users all sorts of trouble with scanning when trying to use HPLIP.

https://forums.linuxmint.com/viewtopic.php?f=51&t=326173

> ty=ET-2750 Series

About 3/4 of the way down the first page is:

> Neither printer would print but the Epson would scan using the "eSCL" driver.
I installed "sane-airscan_0.99.10+68.1_amd64.deb" & "ipp-usb_0.9.10+42.1_amd64.deb" from GitHub

Regards,

Brian.

**Comment by alexpevzner** [comment]
Hi Brian!

> No response (as yet) to two requests for scanimage -L.

Yes. Some users magically disappear once their problem is solved. In this case it doesn't matter, as device seen in Avahi as _uscan._tcp, sane-airscan definitely use it as eSCL.

>> ty=HP LaserJet MFP M28a

This device already known on its M28w incarnation. Seems most, if not all, devices, that support eSCL over network, support it via IPP-over-USB too. Unfortunately, IPP-over-USB doesn't work with WSD (or, at least, I don't know how to get them working together).

>> ty=ET-2750 Series

Strange that driverless IPP printing doesn't work out of box.

I've recently upgraded my work computer from Fedora 29 to Fedora 32, which broke Kyocera closed source print filter (which is not surprising). What is surprising, bringing it to work required noticeable effort and ended with manual addition of the PPD file, downloaded from the Kyocera site. My device can print PostScript and PDF, supporting it without proprietary components should be, in theory, an easy task.

Thank a lot for your effort, Brian! We already have 59 devices in the list. Half of them, I believe, yours!
