### ISSUE TITLE
Canon G3000 series

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#74]
This user has apparently been unable to use his scanner for 10 months.

https://lists.ubuntu.com/archives/ubuntu-users/2020-September/301593.html

The device is not AirPrint-enabled and does not seem to do Bonjour broadcasting. AFAIAC, the issue is solved.

> bas@Viaconsensus-iter:~$ scanimage -L                                                                                      
device `pixma:G3000_192.168.2.12' is a CANON Canon PIXMA G4000 Series                                                      
multi-function peripheral                                                                                                  
device `airscan:w0:Canon G3000 series' is a WSD Canon G3000 series WSD                                                     
network scanner

**Comment by alexpevzner** [comment]
Great! Thank a lot!
