### ISSUE TITLE
HP deskjet 2600 series. EPSON XP-340.

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#76]
Hello Alex,

https://answers.launchpad.net/hplip/+question/692936

> ty=HP DeskJet 2600 series

> Thank you! This worked. It prints better and the scanner actually works
now.

https://forums.linuxmint.com/viewtopic.php?f=51&t=330687&sid=03df11c490dd49a7cfed422539a9c7d0

> ty=EPSON XP-340 Series

> simple-scan "airscan:e0:EPSON XP-340 Series (USB)"
brings up the Document Scanner. When I click on "Scan" in the upper left, it successfully scans. 

Cheers,

Brian.

**Comment by alexpevzner** [comment]
Thank you, Brian!
