### ISSUE TITLE
Officejet 8013, Deskjet 2732, Canon MF642C

### ISSUE THREAD

**Issue by debiantriage** [alexpevzner/sane-airscan#85]
Hello again Alex,

None of these users were able to scan prior to installing sane-airscan.

https://forums.linuxmint.com/viewtopic.php?f=51&t=332264&sid=b5272a48f2bc04ec445598a92eb2939c

> ty=OfficeJet 8010 series

===========================================

https://answers.launchpad.net/hplip/+question/693322

> ty=HP DeskJet 2700 series

===========================================

https://askubuntu.com/questions/1281264/printing-is-not-centered-and-scanner-does-not-work

> device `airscan:e0:Canon MF642C/643C/644C (a5:a7:ce)' is a eSCL Canon MF642C/643C/644C (a5:a7:ce) eSCL network scanner

===========================================

Regards,

Brian.

**Comment by alexpevzner** [comment]
Thank you, Brian!

BTW, we already have Canon MF642C/643C/644C, and alphabetic order of the list doesn't let me to add it twice :-)
