### ISSUE TITLE
Fuzzer fixes

### ISSUE THREAD

**Issue by yetamrra** [alexpevzner/sane-airscan#87]
We've started building fuzzers for sane-airscan.  They've turned up a couple of small bugs and some build warnings so far.  A couple of questions:

1. Should I send fixes here or to the unstable branch?

2. Do you have any interest in the fuzzer targets? I believe they can be built and run locally with clang without any access to the clusterfuzz infrastructure.  We're happy to share them if you find them useful.

**Comment by alexpevzner** [comment]
1. I think, better here
2. I want to look, thank you.

**Comment by alexpevzner** [comment]
Hi!

Is this issue still relevant?

**Comment by yetamrra** [comment]
No, let's close it out.  Thanks for checking in on it.
